apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}-inner
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.innerService.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.innerService.labels }}
    {{ toYaml .Values.innerService.labels | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.innerService.type }}
  externalTrafficPolicy: {{ .Values.innerService.externalTrafficPolicy }}
  {{- if and .Values.innerService.loadBalancerIP (eq .Values.innerService.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.innerService.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.innerService.type "LoadBalancer") .Values.innerService.loadBalancerSourceRanges }}
  {{- with .Values.innerService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if and (eq .Values.innerService.type "ClusterIP") .Values.innerService.clusterIP }}
  clusterIP: {{ .Values.innerService.clusterIP }}
  {{- end }}
  ports:
    - name: https
      port: {{ .Values.innerService.port }}
      targetPort: 5000
      {{- if and .Values.innerService.nodePort (or (eq .Values.innerService.type "NodePort") (eq .Values.innerService.type "LoadBalancer")) }}
      nodePort: {{ .Values.innerService.nodePort }}
      {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  {{- if .Values.podLabels }}
  {{ toYaml .Values.podLabels | indent 2 }}
  {{- end }}