apiVersion: v1
kind: Secret
metadata:
  name: cr-cache-tls-for-https
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  tls.cert: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
type: Opaque